/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Clases.*;
import java.awt.Color;
import EDD.*;
import proyecto_1_edd.*;
/**
 *
 * @author Gustavo
 */
public class Ventana_Remove extends javax.swing.JFrame {
    List Usuarios;
    Ventana_Principal origen;
    /**
     * Creates new form Ventana_Remove
     */
    public Ventana_Remove() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public Ventana_Remove(List lista_grafo, Ventana_Principal origen) {
        initComponents();
        this.setLocationRelativeTo(null);
        Usuarios = lista_grafo;
        this.origen = origen;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton_remove_user = new javax.swing.JButton();
        escribir_user_remove = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        boton_volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boton_remove_user.setText("Eliminar");
        boton_remove_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_remove_userActionPerformed(evt);
            }
        });

        escribir_user_remove.setEditable(false);
        escribir_user_remove.setBackground(new java.awt.Color(255, 255, 255));
        escribir_user_remove.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        escribir_user_remove.setForeground(new java.awt.Color(204, 204, 204));
        escribir_user_remove.setText("Ingrese el nombre de usuario a eliminar...");
        escribir_user_remove.setToolTipText("");
        escribir_user_remove.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        escribir_user_remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                escribir_user_removeMousePressed(evt);
            }
        });
        escribir_user_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escribir_user_removeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel1.setText("USUARIO:");

        boton_volver.setText("Volver al inicio");
        boton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton_volver)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(escribir_user_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(boton_remove_user))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(escribir_user_remove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_remove_user))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(boton_volver)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_remove_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_remove_userActionPerformed
        // TODO add your handling code here:
        if(!escribir_user_remove.getText().equals("Ingrese el nombre de usuario a eliminar...")){
            Usuario.eliminar_usuario(escribir_user_remove.getText(), Usuarios);
        }
        
    }//GEN-LAST:event_boton_remove_userActionPerformed

    private void escribir_user_removeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escribir_user_removeMousePressed
        // TODO add your handling code here:
        escribir_user_remove.setEditable(true);
        if(escribir_user_remove.getText().equals("Ingrese el nombre de usuario a eliminar...")){
            escribir_user_remove.setText("");
            escribir_user_remove.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_escribir_user_removeMousePressed

    private void escribir_user_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escribir_user_removeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escribir_user_removeActionPerformed

    private void boton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_volverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        origen.setVisible(true);
    }//GEN-LAST:event_boton_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Remove().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_remove_user;
    private javax.swing.JButton boton_volver;
    private javax.swing.JTextField escribir_user_remove;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
